name: Build SRCDS TickrateEnabler

on:
  # manual only for now
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        branch:
          - css
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4

      - name: Pull devcontainer image
        run: docker pull ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: store current UID
        run: echo "value=$(id -u)" >> ${GITHUB_OUTPUT}
        id: uid

      - name: Build ${{ matrix.branch }} inside devcontainer image
        run: |
          sudo chown -R 1000 $(pwd)
          docker run --rm -v $(pwd):/src -w /src ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest make ENGINE=${{ matrix.branch }} -j $(nproc)
          sudo chown -R ${{ steps.uid.outputs.value }} $(pwd)
